/*******************************************************************************
 * Auto-generated by TCL Monster
 *
 * @file hw_platform.h
 * @brief Hardware platform definitions for MIV_RV32_BaseDesign
 *
 * Generated: 2025-11-19 17:43:18
 * Project: miv_rv32_demo
 * SmartDesign: MIV_RV32_BaseDesign
 *
 * IMPORTANT: This file is auto-generated from Libero memory map export.
 * Do not edit manually - regenerate from updated Libero design instead.
 ******************************************************************************/

#ifndef HW_PLATFORM_H_
#define HW_PLATFORM_H_

/******************************************************************************
 * Peripheral Base Addresses
 *
 * These addresses are extracted from the SmartDesign memory map.
 * Format: <COMPONENT_NAME>_BASE_ADDR
 *****************************************************************************/

#define COREUARTAPB_BASE_ADDR                             (0x70000000UL)
#define CORETIMER_C0_BASE_ADDR                            (0x70000000UL)
#define CORETIMER_C1_BASE_ADDR                            (0x70000000UL)
#define COREGPIO_BASE_ADDR                                (0x70000000UL)

/******************************************************************************
 * System Clock Frequency
 *
 * TODO: Update this value based on your design's clock configuration
 *****************************************************************************/
#ifndef SYS_CLK_FREQ
#define SYS_CLK_FREQ                            50000000UL
#endif

/******************************************************************************
 * Baud Rate Calculations
 *****************************************************************************/
#define BAUD_VALUE_115200                       ((SYS_CLK_FREQ / (16 * 115200)) - 1)
#define BAUD_VALUE_57600                        ((SYS_CLK_FREQ / (16 * 57600)) - 1)

/******************************************************************************
 * STDIO UART Configuration (Optional)
 *
 * Uncomment and configure if you want printf/scanf redirected to UART
 *****************************************************************************/
/* #define MSCC_STDIO_THRU_CORE_UART_APB */
/* #define MSCC_STDIO_UART_BASE_ADDR          COREUARTAPB0_BASE_ADDR */
/* #define MSCC_STDIO_BAUD_VALUE              BAUD_VALUE_115200 */

#endif /* HW_PLATFORM_H_ */
