# ==============================================================================
# Generate Pin Constraints for MI-V Simple Design
# ==============================================================================
#
# Purpose: Generate PDC file with pin assignments for MPF300 Eval Kit
# Usage: ./run_libero.sh tcl_scripts/generate_constraints.tcl SCRIPT
#
# Reference: MPF300 Eval Kit User Guide
# ==============================================================================

set script_dir [file dirname [info script]]
set project_root [file dirname $script_dir]
set project_name "miv_simple_demo"
set project_location "$project_root/libero_projects/$project_name"

# ==============================================================================
# Helper Functions
# ==============================================================================

proc print_msg {message} {
    puts "=================================================================================="
    puts $message
    puts "=================================================================================="
}

proc print_info {message} {
    puts "INFO: $message"
}

# ==============================================================================
# Pin Assignments for MPF300 Eval Kit
# ==============================================================================

# Reference: MPF300-EVAL-KIT schematic
set pin_assignments {
    {CLK_50MHZ   "AE20"  "LVCMOS18"   "System clock 50 MHz oscillator"}
    {RESET_N     "AF20"  "LVCMOS18"   "Push button SW1 (active low)"}
    {UART_RX     "L27"   "LVCMOS18"   "UART receive from USB-UART bridge"}
    {UART_TX     "M27"   "LVCMOS18"   "UART transmit to USB-UART bridge"}
    {LED_1       "P15"   "LVCMOS18"   "LED DS1 (active high)"}
    {LED_2       "P16"   "LVCMOS18"   "LED DS2 (active high)"}
    {LED_3       "P17"   "LVCMOS18"   "LED DS3 (active high)"}
    {LED_4       "P18"   "LVCMOS18"   "LED DS4 (active high)"}
    {TCK         "J24"   "LVCMOS18"   "JTAG TCK"}
    {TDI         "H23"   "LVCMOS18"   "JTAG TDI"}
    {TDO         "H24"   "LVCMOS18"   "JTAG TDO"}
    {TMS         "J23"   "LVCMOS18"   "JTAG TMS"}
    {TRSTB       "K24"   "LVCMOS18"   "JTAG TRSTB (active low)"}
}

# ==============================================================================
# Main Script
# ==============================================================================

print_msg "Generating Pin Constraints for MI-V Simple Design"

# Check if project exists
if {![file exists "$project_location/${project_name}.prjx"]} {
    print_msg "ERROR: Project not found at $project_location"
    print_info "Please run create_miv_simple.tcl first."
    exit 1
}

# Open existing project
print_info "Opening project: $project_location"
open_project "$project_location/${project_name}.prjx"

# Create PDC file
set pdc_file "$project_location/constraint/io_constraints.pdc"
file mkdir [file dirname $pdc_file]

print_info "Generating PDC file: $pdc_file"

set fd [open $pdc_file w]
puts $fd "# =============================================================================="
puts $fd "# Pin Constraints for MI-V Simple Design - MPF300 Eval Kit"
puts $fd "# =============================================================================="
puts $fd "#"
puts $fd "# Auto-generated by: generate_constraints.tcl"
puts $fd "# Date: [clock format [clock seconds]]"
puts $fd "#"
puts $fd "# Target Board: MPF300-EVAL-KIT"
puts $fd "# Device: MPF300TS-FCG1152"
puts $fd "#"
puts $fd "# =============================================================================="
puts $fd ""

foreach pin_info $pin_assignments {
    lassign $pin_info port_name pin_num io_std comment

    puts $fd "# $comment"
    puts $fd "set_io -port_name {$port_name} \\"
    puts $fd "       -pin_name {$pin_num} \\"
    puts $fd "       -fixed {true} \\"
    puts $fd "       -io_std {$io_std}"
    puts $fd ""
}

puts $fd "# =============================================================================="
puts $fd "# End of constraints"
puts $fd "# =============================================================================="

close $fd

print_info "PDC file generated successfully"

# Import PDC file into project
print_info "Importing PDC file into project..."
create_links \
    -io_pdc "$pdc_file"

print_msg "Pin Constraints Generated!"
print_info ""
print_info "PDC file: $pdc_file"
print_info ""
print_info "Next steps:"
print_info "1. Review pin assignments"
print_info "2. Rebuild design with constraints"
print_info "3. Verify pin placement in reports"

save_project
close_project
