# ==============================================================================
# PF_CCC Configuration Generator
# ==============================================================================
#
# Purpose: Generate PF_CCC (Clock Conditioning Circuit) configurations
# Approach: Template-based for common scenarios (GUI handles complex PLL math)
# Usage:   source tcl_scripts/lib/generators/ccc_config_generator.tcl
#
# ==============================================================================

# ==============================================================================
# Template-Based CCC Generation
# ==============================================================================

proc generate_ccc_single_output {args} {
    # Generate CCC with single output clock
    # Example: 50 MHz input → 50 MHz output

    array set opts {
        -input_freq "50"
        -output_freq "50"
        -component_name "PF_CCC_C0"
        -output_file ""
    }

    foreach {key value} $args {
        if {[info exists opts($key)]} {
            set opts($key) $value
        }
    }

    # Calculate divider (simple case for bypass or integer division)
    set divider [expr {int($opts(-input_freq) / $opts(-output_freq))}]
    if {$divider < 1} {set divider 1}

    set config "# Exporting core $opts(-component_name) to TCL\n"
    append config "# Configuration: $opts(-input_freq) MHz → $opts(-output_freq) MHz\n"
    append config "# Auto-generated by CCC Configuration Generator\n"
    append config "create_and_configure_core -core_vlnv {Actel:SgCore:PF_CCC:*} -download_core -component_name {$opts(-component_name)} -params {\\\n"

    # Minimal DLL configuration (disabled for simple clock division)
    append config "\"DLL_CLK_0_BANKCLK_EN:false\"  \\\n"
    append config "\"DLL_CLK_0_DEDICATED_EN:false\"  \\\n"
    append config "\"DLL_CLK_0_FABCLK_EN:false\"  \\\n"
    append config "\"DLL_CLK_1_BANKCLK_EN:false\"  \\\n"
    append config "\"DLL_CLK_1_DEDICATED_EN:false\"  \\\n"
    append config "\"DLL_CLK_1_FABCLK_EN:false\"  \\\n"
    append config "\"DLL_CLK_P_EN:false\"  \\\n"
    append config "\"DLL_CLK_P_OPTIONS_EN:false\"  \\\n"
    append config "\"DLL_CLK_REF_OPTION:DIVIDE_BY_1\"  \\\n"
    append config "\"DLL_CLK_REF_OPTIONS_EN:false\"  \\\n"
    append config "\"DLL_CLK_S_EN:false\"  \\\n"
    append config "\"DLL_CLK_S_OPTION:DIVIDE_BY_1\"  \\\n"
    append config "\"DLL_CLK_S_OPTIONS_EN:false\"  \\\n"

    # GL0_0 (Output 0) - Enabled
    append config "\"GL0_0_BANKCLK_USED:false\"  \\\n"
    append config "\"GL0_0_BYPASS:0\"  \\\n"
    append config "\"GL0_0_BYPASS_EN:false\"  \\\n"
    append config "\"GL0_0_DEDICATED_USED:false\"  \\\n"
    append config "\"GL0_0_DIV:$divider\"  \\\n"
    append config "\"GL0_0_DIVSTART:0\"  \\\n"
    append config "\"GL0_0_FABCLK_GATED_USED:false\"  \\\n"
    append config "\"GL0_0_FABCLK_USED:true\"  \\\n"
    append config "\"GL0_0_IS_USED:true\"  \\\n"
    append config "\"GL0_0_OUT_FREQ:$opts(-output_freq)\"  \\\n"
    append config "\"GL0_0_PHASE_INDEX:0\"  \\\n"

    # GL0_1 through GL3_1 - All disabled
    foreach gl {GL0_1 GL1_0 GL1_1 GL2_0 GL2_1 GL3_0 GL3_1} {
        append config "\"${gl}_IS_USED:false\"  \\\n"
        append config "\"${gl}_FABCLK_USED:false\"  \\\n"
    }

    # PLL configuration
    append config "\"PLL_IN_FREQ_0:$opts(-input_freq)\"  \\\n"
    append config "\"PLL_FEEDBACK_MODE_0:Post-VCO\"  \\\n"
    append config "\"PLL_VCO_MODE_0:MIN_JITTER\"  \\\n"
    append config "\"PLL_REFDIV_0:4\"  }\n"

    append config "# Exporting core $opts(-component_name) to TCL done\n"

    # Output
    if {$opts(-output_file) != ""} {
        set fp [open $opts(-output_file) w]
        puts $fp $config
        close $fp
        puts "Generated CCC configuration: $opts(-output_file)"
        puts "  Input: $opts(-input_freq) MHz"
        puts "  Output: $opts(-output_freq) MHz (GL0_0)"
    } else {
        puts $config
    }

    return $config
}

proc generate_ccc_dual_output {args} {
    # Generate CCC with dual outputs
    # Example: 50 MHz input → 50 MHz (OUT0) + 200 MHz (OUT1)
    # This is the configuration needed for MI-V + DDR

    array set opts {
        -input_freq "50"
        -output0_freq "50"
        -output1_freq "200"
        -component_name "PF_CCC_C1"
        -output_file ""
    }

    foreach {key value} $args {
        if {[info exists opts($key)]} {
            set opts($key) $value
        }
    }

    # For dual outputs with multiplication, we need PLL
    # Calculate multiplier to reach highest output frequency
    set max_freq [expr {max($opts(-output0_freq), $opts(-output1_freq))}]
    set multiplier [expr {int($max_freq / $opts(-input_freq))}]
    if {$multiplier < 1} {set multiplier 1}

    # Calculate dividers for each output from VCO
    set vco_freq [expr {$opts(-input_freq) * $multiplier}]
    set div0 [expr {int($vco_freq / $opts(-output0_freq))}]
    set div1 [expr {int($vco_freq / $opts(-output1_freq))}]

    puts "INFO: PLL Configuration"
    puts "  VCO Frequency: $vco_freq MHz (input $opts(-input_freq) MHz × $multiplier)"
    puts "  Output 0: $vco_freq MHz ÷ $div0 = [expr {$vco_freq / $div0}] MHz"
    puts "  Output 1: $vco_freq MHz ÷ $div1 = [expr {$vco_freq / $div1}] MHz"

    set config "# Exporting core $opts(-component_name) to TCL\n"
    append config "# Configuration: $opts(-input_freq) MHz → $opts(-output0_freq) MHz (OUT0) + $opts(-output1_freq) MHz (OUT1)\n"
    append config "# Auto-generated by CCC Configuration Generator\n"
    append config "# PLL: VCO=$vco_freq MHz, Multiplier=$multiplier, Div0=$div0, Div1=$div1\n"
    append config "create_and_configure_core -core_vlnv {Actel:SgCore:PF_CCC:*} -download_core -component_name {$opts(-component_name)} -params {\\\n"

    # Minimal DLL configuration
    append config "\"DLL_CLK_0_BANKCLK_EN:false\"  \\\n"
    append config "\"DLL_CLK_0_DEDICATED_EN:false\"  \\\n"
    append config "\"DLL_CLK_0_FABCLK_EN:false\"  \\\n"
    append config "\"DLL_CLK_1_BANKCLK_EN:false\"  \\\n"
    append config "\"DLL_CLK_1_DEDICATED_EN:false\"  \\\n"
    append config "\"DLL_CLK_1_FABCLK_EN:false\"  \\\n"
    append config "\"DLL_CLK_P_EN:false\"  \\\n"

    # GL0_0 (Output 0) - System clock
    append config "\"GL0_0_BANKCLK_USED:false\"  \\\n"
    append config "\"GL0_0_DIV:$div0\"  \\\n"
    append config "\"GL0_0_FABCLK_USED:true\"  \\\n"
    append config "\"GL0_0_IS_USED:true\"  \\\n"
    append config "\"GL0_0_OUT_FREQ:$opts(-output0_freq)\"  \\\n"

    # GL0_1 (Output 1) - DDR AXI clock
    append config "\"GL0_1_BANKCLK_USED:false\"  \\\n"
    append config "\"GL0_1_DIV:$div1\"  \\\n"
    append config "\"GL0_1_FABCLK_USED:true\"  \\\n"
    append config "\"GL0_1_IS_USED:true\"  \\\n"
    append config "\"GL0_1_OUT_FREQ:$opts(-output1_freq)\"  \\\n"

    # GL1_0 through GL3_1 - Disabled
    foreach gl {GL1_0 GL1_1 GL2_0 GL2_1 GL3_0 GL3_1} {
        append config "\"${gl}_IS_USED:false\"  \\\n"
        append config "\"${gl}_FABCLK_USED:false\"  \\\n"
    }

    # PLL configuration
    append config "\"PLL_IN_FREQ_0:$opts(-input_freq)\"  \\\n"
    append config "\"PLL_FEEDBACK_MODE_0:Post-VCO\"  \\\n"
    append config "\"PLL_VCO_MODE_0:MIN_JITTER\"  \\\n"
    append config "\"PLL_REFDIV_0:4\"  }\n"

    append config "# Exporting core $opts(-component_name) to TCL done\n"
    append config "# NOTE: This is a simplified configuration. For production use, verify in Libero GUI.\n"

    # Output
    if {$opts(-output_file) != ""} {
        set fp [open $opts(-output_file) w]
        puts $fp $config
        close $fp
        puts "Generated CCC configuration: $opts(-output_file)"
        puts "  Input: $opts(-input_freq) MHz"
        puts "  Output 0 (GL0_0): $opts(-output0_freq) MHz"
        puts "  Output 1 (GL0_1): $opts(-output1_freq) MHz"
    } else {
        puts $config
    }

    return $config
}

# ==============================================================================
# Convenience Functions for Common Configurations
# ==============================================================================

proc generate_miv_ccc {{component_name "PF_CCC_C0"} {output_file ""}} {
    # Standard MI-V system clock: 50 MHz in → 50 MHz out
    generate_ccc_single_output \
        -input_freq "50" \
        -output_freq "50" \
        -component_name $component_name \
        -output_file $output_file
}

proc generate_miv_ddr_ccc {{component_name "PF_CCC_C1"} {output_file ""}} {
    # MI-V + DDR system: 50 MHz in → 50 MHz (system) + 200 MHz (DDR AXI)
    generate_ccc_dual_output \
        -input_freq "50" \
        -output0_freq "50" \
        -output1_freq "200" \
        -component_name $component_name \
        -output_file $output_file
}

puts "PF_CCC Configuration Generator loaded"
puts "Usage:"
puts "  generate_ccc_single_output -input_freq \"50\" -output_freq \"50\" -output_file \"my_ccc.tcl\""
puts "  generate_ccc_dual_output -input_freq \"50\" -output0_freq \"50\" -output1_freq \"200\" -output_file \"my_ccc.tcl\""
puts ""
puts "Convenience functions:"
puts "  generate_miv_ccc \"PF_CCC_C0\" \"output.tcl\"        # 50 MHz single output"
puts "  generate_miv_ddr_ccc \"PF_CCC_C1\" \"output.tcl\"    # 50 MHz + 200 MHz dual output"
puts ""
puts "NOTE: Generated configurations are simplified. For production, verify in Libero GUI."
