# ==============================================================================
# CoreGPIO Configuration Generator
# ==============================================================================
#
# Purpose: Generate CoreGPIO (General Purpose I/O) configurations
# Usage:   source tcl_scripts/lib/generators/gpio_config_generator.tcl
#
# ==============================================================================

# ==============================================================================
# Main GPIO Configuration Generator
# ==============================================================================

proc generate_gpio_config {args} {
    # Generate CoreGPIO configuration
    # Supports input, output, or bidirectional GPIO

    array set opts {
        -num_pins "8"
        -direction "output"
        -apb_width "32"
        -initial_values {}
        -component_name "CoreGPIO_C0"
        -output_file ""
    }

    foreach {key value} $args {
        if {[info exists opts($key)]} {
            set opts($key) $value
        } else {
            puts "ERROR: Unknown option $key"
            return
        }
    }

    # Validate num_pins (1 to 32)
    if {$opts(-num_pins) < 1 || $opts(-num_pins) > 32} {
        puts "ERROR: num_pins must be between 1 and 32"
        return
    }

    # Map direction to IO_TYPE values
    # 0 = Input, 1 = Output, 2 = Bidirectional
    set io_type 1
    switch $opts(-direction) {
        "input"  { set io_type 0 }
        "output" { set io_type 1 }
        "bidir"  { set io_type 2 }
        "bidirectional" { set io_type 2 }
        default {
            puts "WARNING: Unknown direction '$opts(-direction)', using 'output'"
            set io_type 1
        }
    }

    # Handle initial values
    if {[llength $opts(-initial_values)] == 0} {
        # Default: all zeros
        for {set i 0} {$i < $opts(-num_pins)} {incr i} {
            lappend opts(-initial_values) 0
        }
    } elseif {[llength $opts(-initial_values)] != $opts(-num_pins)} {
        puts "ERROR: initial_values length ([llength $opts(-initial_values)]) must match num_pins ($opts(-num_pins))"
        return
    }

    # Generate configuration
    set config "# Exporting Component Description of $opts(-component_name) to TCL\n"
    append config "# Auto-generated by GPIO Configuration Generator\n"
    append config "# Configuration: $opts(-num_pins) pins, $opts(-direction)\n"
    append config "# Family: PolarFire\n"
    append config "create_and_configure_core -core_vlnv Actel:DirectCore:CoreGPIO:* -component_name {$opts(-component_name)} -params {\\\n"

    # APB width
    append config "\"APB_WIDTH:$opts(-apb_width)\"  \\\n"

    # Fixed configuration flags (all pins have same config in this generator)
    for {set i 0} {$i < 32} {incr i} {
        set is_fixed [expr {$i < $opts(-num_pins) ? "true" : "false"}]
        append config "\"FIXED_CONFIG_$i:$is_fixed\"  \\\n"
    }

    # Interrupt bus (disabled for simplicity)
    append config "\"INT_BUS:0\"  \\\n"

    # Interrupt types (7 = no interrupt)
    for {set i 0} {$i < 32} {incr i} {
        append config "\"IO_INT_TYPE_$i:7\"  \\\n"
    }

    # Number of used pins
    append config "\"IO_NUM:$opts(-num_pins)\"  \\\n"

    # IO types (input/output/bidir)
    for {set i 0} {$i < 32} {incr i} {
        set type [expr {$i < $opts(-num_pins) ? $io_type : 0}]
        append config "\"IO_TYPE_$i:$type\"  \\\n"
    }

    # Initial values
    for {set i 0} {$i < 32} {incr i} {
        set val [expr {$i < $opts(-num_pins) ? [lindex $opts(-initial_values) $i] : 0}]
        append config "\"IO_VAL_$i:$val\"  \\\n"
    }

    # Output enable type (1 = software controlled)
    append config "\"OE_TYPE:1\"   }\n"

    append config "# Exporting Component Description of $opts(-component_name) to TCL done\n"

    # Output
    if {$opts(-output_file) != ""} {
        set fp [open $opts(-output_file) w]
        puts $fp $config
        close $fp
        puts "Generated GPIO configuration: $opts(-output_file)"
        puts "  Pins: $opts(-num_pins)"
        puts "  Direction: $opts(-direction)"
        if {$io_type == 1} {
            puts "  Initial values: [join $opts(-initial_values) { }]"
        }
    } else {
        puts $config
    }

    return $config
}

# ==============================================================================
# Convenience Functions for Common Configurations
# ==============================================================================

proc generate_gpio_leds {{num_leds "8"} {component_name "CoreGPIO_OUT"} {output_file ""}} {
    # GPIO output for LEDs (all initially off)
    set initial_vals {}
    for {set i 0} {$i < $num_leds} {incr i} {
        lappend initial_vals 0
    }

    generate_gpio_config \
        -num_pins $num_leds \
        -direction "output" \
        -initial_values $initial_vals \
        -component_name $component_name \
        -output_file $output_file
}

proc generate_gpio_buttons {{num_buttons "4"} {component_name "CoreGPIO_IN"} {output_file ""}} {
    # GPIO input for buttons/switches
    generate_gpio_config \
        -num_pins $num_buttons \
        -direction "input" \
        -component_name $component_name \
        -output_file $output_file
}

proc generate_gpio_bidir {{num_pins "8"} {component_name "CoreGPIO_BIDIR"} {output_file ""}} {
    # Bidirectional GPIO
    set initial_vals {}
    for {set i 0} {$i < $num_pins} {incr i} {
        lappend initial_vals 0
    }

    generate_gpio_config \
        -num_pins $num_pins \
        -direction "bidirectional" \
        -initial_values $initial_vals \
        -component_name $component_name \
        -output_file $output_file
}

proc generate_gpio_output_pattern {num_pins pattern {component_name "CoreGPIO_OUT"} {output_file ""}} {
    # GPIO output with specific initial pattern
    # pattern should be a list of 0s and 1s

    if {[llength $pattern] != $num_pins} {
        puts "ERROR: Pattern length ([llength $pattern]) must match num_pins ($num_pins)"
        return
    }

    generate_gpio_config \
        -num_pins $num_pins \
        -direction "output" \
        -initial_values $pattern \
        -component_name $component_name \
        -output_file $output_file
}

puts "CoreGPIO Configuration Generator loaded"
puts "Usage:"
puts "  generate_gpio_config -num_pins \"8\" -direction \"output\" -output_file \"my_gpio.tcl\""
puts ""
puts "Convenience functions:"
puts "  generate_gpio_leds 8 \"CoreGPIO_OUT\" \"gpio_leds.tcl\"        # 8 LED outputs"
puts "  generate_gpio_buttons 4 \"CoreGPIO_IN\" \"gpio_buttons.tcl\"   # 4 button inputs"
puts "  generate_gpio_bidir 8 \"CoreGPIO_BIDIR\" \"gpio_bidir.tcl\"    # 8 bidirectional pins"
puts "  generate_gpio_output_pattern 4 {1 0 1 0} \"CoreGPIO_OUT\" \"gpio_pattern.tcl\""
puts ""
puts "Directions: input, output, bidirectional"
puts "Max pins: 32"
