# ==============================================================================
# PF_PCIE Configuration Generator
# ==============================================================================
#
# Purpose: Generate PF_PCIE (PCIe controller) configurations
# Approach: Template-based for common scenarios (complexity requires GUI for full config)
# Usage:   source tcl_scripts/lib/generators/pcie_config_generator.tcl
#
# Note: PCIe has 200+ parameters. This generator provides working templates for
#       common use cases. For advanced configuration, use Libero GUI.
#
# ==============================================================================

# ==============================================================================
# Template-Based PCIe Generation
# ==============================================================================

proc generate_pcie_endpoint {args} {
    # Generate PCIe Endpoint configuration (device that connects to host)

    array set opts {
        -num_lanes "1"
        -speed "Gen1"
        -bar0_size "4 KB"
        -device_id "0x1556"
        -vendor_id "0x11AA"
        -ref_clk_freq "100"
        -component_name "PF_PCIE_EP"
        -output_file ""
    }

    foreach {key value} $args {
        if {[info exists opts($key)]} {
            set opts($key) $value
        }
    }

    # Validate num_lanes
    set lane_config "x$opts(-num_lanes)"
    if {$opts(-num_lanes) ni {1 2 4}} {
        puts "ERROR: num_lanes must be 1, 2, or 4"
        return
    }

    # Generate configuration
    set config "# Exporting Component Description of $opts(-component_name) to TCL\n"
    append config "# Auto-generated by PCIe Configuration Generator\n"
    append config "# Configuration: Endpoint, $lane_config lanes, $opts(-speed) (2.5 Gbps)\n"
    append config "# BAR0: $opts(-bar0_size), Device ID: $opts(-device_id)\n"
    append config "# Family: PolarFire or PolarFireSoC\n"
    append config "create_and_configure_core -core_vlnv {Actel:SgCore:PF_PCIE:*} -component_name {$opts(-component_name)} -params {\\\n"

    # Basic configuration
    append config "\"EXPOSE_ALL_DEBUG_PORTS:false\"  \\\n"
    append config "\"UI_DLL_JITTER_TOLERANCE:Medium_Low\"  \\\n"
    append config "\"UI_EXPOSE_LANE_DRI_PORTS:true\"  \\\n"
    append config "\"UI_IS_CONFIGURED:true\"  \\\n"

    # PCIE_0 (Main controller for Endpoint)
    append config "\"UI_PCIE_0_BAR_MODE:Custom\"  \\\n"
    append config "\"UI_PCIE_0_CDR_REF_CLK_NUMBER:1\"  \\\n"
    append config "\"UI_PCIE_0_CDR_REF_CLK_SOURCE:Dedicated\"  \\\n"
    append config "\"UI_PCIE_0_CLASS_CODE:0x0000\"  \\\n"
    append config "\"UI_PCIE_0_CONTROLLER_ENABLED:Enabled\"  \\\n"
    append config "\"UI_PCIE_0_DE_EMPHASIS:-3.5 dB\"  \\\n"
    append config "\"UI_PCIE_0_DEVICE_ID:$opts(-device_id)\"  \\\n"
    append config "\"UI_PCIE_0_EXPOSE_WAKE_SIG:Disabled\"  \\\n"
    append config "\"UI_PCIE_0_INTERRUPTS:MSI1\"  \\\n"
    append config "\"UI_PCIE_0_L0_ACC_LATENCY:No limit\"  \\\n"
    append config "\"UI_PCIE_0_L0_EXIT_LATENCY:64 ns to less than 128 ns\"  \\\n"
    append config "\"UI_PCIE_0_L1_ACC_LATENCY:No limit\"  \\\n"
    append config "\"UI_PCIE_0_L1_ENABLE:Disabled\"  \\\n"
    append config "\"UI_PCIE_0_L1_EXIT_LATENCY:16 us to less than 32 us\"  \\\n"
    append config "\"UI_PCIE_0_LANE_RATE:$opts(-speed) (2.5 Gbps)\"  \\\n"

    # BAR configuration (BAR0 enabled, others disabled)
    append config "\"UI_PCIE_0_MASTER_SIZE_BAR_0_TABLE:$opts(-bar0_size)\"  \\\n"
    append config "\"UI_PCIE_0_MASTER_TYPE_BAR_0_TABLE:64-bit prefetchable memory\"  \\\n"
    for {set i 1} {$i <= 5} {incr i} {
        append config "\"UI_PCIE_0_MASTER_SIZE_BAR_${i}_TABLE:4 KB\"  \\\n"
        append config "\"UI_PCIE_0_MASTER_TYPE_BAR_${i}_TABLE:Disabled\"  \\\n"
    }

    append config "\"UI_PCIE_0_NUM_FTS:63\"  \\\n"
    append config "\"UI_PCIE_0_NUMBER_OF_LANES:$lane_config\"  \\\n"
    append config "\"UI_PCIE_0_PHY_REF_CLK_SLOT:Slot\"  \\\n"
    append config "\"UI_PCIE_0_PORT_TYPE:End Point\"  \\\n"
    append config "\"UI_PCIE_0_REF_CLK_FREQ:$opts(-ref_clk_freq)\"  \\\n"
    append config "\"UI_PCIE_0_REVISION_ID:0x0000\"  \\\n"

    # Slave tables (all disabled for simple endpoint)
    for {set i 0} {$i <= 7} {incr i} {
        append config "\"UI_PCIE_0_SLAVE_STATE_TABLE_${i}:Disabled\"  \\\n"
    }

    append config "\"UI_PCIE_0_SUB_SYSTEM_ID:0x0000\"  \\\n"
    append config "\"UI_PCIE_0_SUB_VENDOR_ID:0x0000\"  \\\n"
    append config "\"UI_PCIE_0_TRANSMIT_SWING:Full Swing\"  \\\n"
    append config "\"UI_PCIE_0_VENDOR_ID:$opts(-vendor_id)\"  \\\n"

    # PCIE_1 (disabled for simple endpoint)
    append config "\"UI_PCIE_1_CONTROLLER_ENABLED:Disabled\"  \\\n"

    # Lane usage
    for {set i 0} {$i < 4} {incr i} {
        set lane_used [expr {$i < $opts(-num_lanes) ? "true" : "false"}]
        append config "\"UI_PCIESS_LANE${i}_IS_USED:$lane_used\"  \\\n"
    }

    # GPSS lanes (disabled)
    for {set i 0} {$i < 4} {incr i} {
        append config "\"UI_GPSS1_LANE${i}_IS_USED:false\"  \\\n"
    }

    append config "\"UI_PROTOCOL_PRESET_USED:PCIe\"  \\\n"
    append config "\"UI_SIMULATION_LEVEL:RTL\"  \\\n"
    append config "\"UI_TX_CLK_DIV_FACTOR:1\"  \\\n"
    append config "\"UI_USE_EMBEDDED_DLL:true\"  \\\n"
    append config "\"XT_ES_DEVICE:false\"   }\n"

    append config "# Exporting Component Description of $opts(-component_name) to TCL done\n"
    append config "# NOTE: This is a simplified configuration for common use cases.\n"
    append config "#       For advanced features (multiple BARs, MSI-X, AER, etc.), use Libero GUI.\n"

    # Output
    if {$opts(-output_file) != ""} {
        set fp [open $opts(-output_file) w]
        puts $fp $config
        close $fp
        puts "Generated PCIe Endpoint configuration: $opts(-output_file)"
        puts "  Lanes: $lane_config"
        puts "  Speed: $opts(-speed) (2.5 Gbps)"
        puts "  BAR0: $opts(-bar0_size)"
        puts "  Device ID: $opts(-device_id), Vendor ID: $opts(-vendor_id)"
    } else {
        puts $config
    }

    return $config
}

proc generate_pcie_root_port {args} {
    # Generate PCIe Root Port configuration (host controller)

    array set opts {
        -num_lanes "4"
        -speed "Gen2"
        -bar0_size "2 GB"
        -device_id "0x1556"
        -vendor_id "0x11AA"
        -ref_clk_freq "100"
        -component_name "PF_PCIE_RP"
        -output_file ""
    }

    foreach {key value} $args {
        if {[info exists opts($key)]} {
            set opts($key) $value
        }
    }

    # Validate num_lanes
    set lane_config "x$opts(-num_lanes)"
    if {$opts(-num_lanes) ni {1 2 4}} {
        puts "ERROR: num_lanes must be 1, 2, or 4"
        return
    }

    # Map speed to description
    set speed_desc "5.0 Gbps"
    if {$opts(-speed) eq "Gen1"} {
        set speed_desc "2.5 Gbps"
    }

    # Generate configuration
    set config "# Exporting Component Description of $opts(-component_name) to TCL\n"
    append config "# Auto-generated by PCIe Configuration Generator\n"
    append config "# Configuration: Root Port, $lane_config lanes, $opts(-speed) ($speed_desc)\n"
    append config "# BAR0: $opts(-bar0_size), Device ID: $opts(-device_id)\n"
    append config "# Family: PolarFire or PolarFireSoC\n"
    append config "create_and_configure_core -core_vlnv {Actel:SgCore:PF_PCIE:*} -component_name {$opts(-component_name)} -params {\\\n"

    # Basic configuration
    append config "\"EXPOSE_ALL_DEBUG_PORTS:false\"  \\\n"
    append config "\"UI_DLL_JITTER_TOLERANCE:Medium_Low\"  \\\n"
    append config "\"UI_EXPOSE_LANE_DRI_PORTS:true\"  \\\n"
    append config "\"UI_IS_CONFIGURED:true\"  \\\n"

    # PCIE_0 (Disabled for Root Port configuration - PCIE_1 is used)
    append config "\"UI_PCIE_0_CONTROLLER_ENABLED:Disabled\"  \\\n"

    # PCIE_1 (Main controller for Root Port)
    append config "\"UI_PCIE_1_BAR_MODE:Custom\"  \\\n"
    append config "\"UI_PCIE_1_CDR_REF_CLK_NUMBER:1\"  \\\n"
    append config "\"UI_PCIE_1_CDR_REF_CLK_SOURCE:Dedicated\"  \\\n"
    append config "\"UI_PCIE_1_CLASS_CODE:0x0604\"  \\\n"
    append config "\"UI_PCIE_1_CONTROLLER_ENABLED:Enabled\"  \\\n"
    append config "\"UI_PCIE_1_DE_EMPHASIS:-3.5 dB\"  \\\n"
    append config "\"UI_PCIE_1_DEVICE_ID:$opts(-device_id)\"  \\\n"
    append config "\"UI_PCIE_1_EXPOSE_WAKE_SIG:Disabled\"  \\\n"
    append config "\"UI_PCIE_1_INTERRUPTS:MSI8\"  \\\n"
    append config "\"UI_PCIE_1_L0_ACC_LATENCY:No limit\"  \\\n"
    append config "\"UI_PCIE_1_L0_EXIT_LATENCY:64 ns to less than 128 ns\"  \\\n"
    append config "\"UI_PCIE_1_L1_ACC_LATENCY:No limit\"  \\\n"
    append config "\"UI_PCIE_1_L1_ENABLE:Disabled\"  \\\n"
    append config "\"UI_PCIE_1_L1_EXIT_LATENCY:16 us to less than 32 us\"  \\\n"
    append config "\"UI_PCIE_1_LANE_RATE:$opts(-speed) ($speed_desc)\"  \\\n"

    # BAR configuration
    append config "\"UI_PCIE_1_MASTER_SIZE_BAR_0_TABLE:$opts(-bar0_size)\"  \\\n"
    append config "\"UI_PCIE_1_MASTER_TYPE_BAR_0_TABLE:64-bit prefetchable memory\"  \\\n"
    for {set i 1} {$i <= 5} {incr i} {
        append config "\"UI_PCIE_1_MASTER_SIZE_BAR_${i}_TABLE:4 KB\"  \\\n"
        append config "\"UI_PCIE_1_MASTER_TYPE_BAR_${i}_TABLE:Disabled\"  \\\n"
    }

    append config "\"UI_PCIE_1_NUM_FTS:63\"  \\\n"
    append config "\"UI_PCIE_1_NUMBER_OF_LANES:$lane_config\"  \\\n"
    append config "\"UI_PCIE_1_PHY_REF_CLK_SLOT:Slot\"  \\\n"
    append config "\"UI_PCIE_1_PORT_TYPE:Root Port\"  \\\n"
    append config "\"UI_PCIE_1_REF_CLK_FREQ:$opts(-ref_clk_freq)\"  \\\n"
    append config "\"UI_PCIE_1_REVISION_ID:0x0000\"  \\\n"

    # Slave table (table 0 enabled for root port)
    append config "\"UI_PCIE_1_SLAVE_STATE_TABLE_0:Enabled\"  \\\n"
    for {set i 1} {$i <= 7} {incr i} {
        append config "\"UI_PCIE_1_SLAVE_STATE_TABLE_${i}:Disabled\"  \\\n"
    }

    append config "\"UI_PCIE_1_SUB_SYSTEM_ID:0x0000\"  \\\n"
    append config "\"UI_PCIE_1_SUB_VENDOR_ID:0x0000\"  \\\n"
    append config "\"UI_PCIE_1_TRANSMIT_SWING:Full Swing\"  \\\n"
    append config "\"UI_PCIE_1_VENDOR_ID:$opts(-vendor_id)\"  \\\n"

    # Lane usage
    for {set i 0} {$i < 4} {incr i} {
        set lane_used [expr {$i < $opts(-num_lanes) ? "true" : "false"}]
        append config "\"UI_PCIESS_LANE${i}_IS_USED:$lane_used\"  \\\n"
    }

    # GPSS lanes (disabled)
    for {set i 0} {$i < 4} {incr i} {
        append config "\"UI_GPSS1_LANE${i}_IS_USED:false\"  \\\n"
    }

    append config "\"UI_PROTOCOL_PRESET_USED:PCIe\"  \\\n"
    append config "\"UI_SIMULATION_LEVEL:RTL\"  \\\n"
    append config "\"UI_TX_CLK_DIV_FACTOR:1\"  \\\n"
    append config "\"UI_USE_EMBEDDED_DLL:true\"  \\\n"
    append config "\"XT_ES_DEVICE:false\"   }\n"

    append config "# Exporting Component Description of $opts(-component_name) to TCL done\n"
    append config "# NOTE: This is a simplified configuration for common use cases.\n"
    append config "#       For advanced features (AER, hotplug, ASPM, etc.), use Libero GUI.\n"

    # Output
    if {$opts(-output_file) != ""} {
        set fp [open $opts(-output_file) w]
        puts $fp $config
        close $fp
        puts "Generated PCIe Root Port configuration: $opts(-output_file)"
        puts "  Lanes: $lane_config"
        puts "  Speed: $opts(-speed) ($speed_desc)"
        puts "  BAR0: $opts(-bar0_size)"
        puts "  Device ID: $opts(-device_id), Vendor ID: $opts(-vendor_id)"
    } else {
        puts $config
    }

    return $config
}

# ==============================================================================
# Convenience Functions for Common Configurations
# ==============================================================================

proc generate_pcie_ep_x1_gen1 {{component_name "PF_PCIE_EP_X1"} {output_file ""}} {
    # Simple x1 Gen1 Endpoint (most common for add-in cards)
    generate_pcie_endpoint \
        -num_lanes 1 \
        -speed "Gen1" \
        -bar0_size "4 KB" \
        -component_name $component_name \
        -output_file $output_file
}

proc generate_pcie_ep_x4_gen2 {{component_name "PF_PCIE_EP_X4"} {output_file ""}} {
    # x4 Gen2 Endpoint (higher performance)
    generate_pcie_endpoint \
        -num_lanes 4 \
        -speed "Gen2" \
        -bar0_size "1 MB" \
        -component_name $component_name \
        -output_file $output_file
}

proc generate_pcie_rp_x4_gen2 {{component_name "PF_PCIE_RP_X4"} {output_file ""}} {
    # x4 Gen2 Root Port (host controller)
    generate_pcie_root_port \
        -num_lanes 4 \
        -speed "Gen2" \
        -bar0_size "2 GB" \
        -component_name $component_name \
        -output_file $output_file
}

puts "PF_PCIE Configuration Generator loaded"
puts "Usage:"
puts "  generate_pcie_endpoint -num_lanes \"1\" -speed \"Gen1\" -output_file \"my_pcie_ep.tcl\""
puts "  generate_pcie_root_port -num_lanes \"4\" -speed \"Gen2\" -output_file \"my_pcie_rp.tcl\""
puts ""
puts "Convenience functions:"
puts "  generate_pcie_ep_x1_gen1 \"PF_PCIE_EP\" \"pcie_ep_x1.tcl\"   # Simple x1 Gen1 endpoint"
puts "  generate_pcie_ep_x4_gen2 \"PF_PCIE_EP\" \"pcie_ep_x4.tcl\"   # x4 Gen2 endpoint"
puts "  generate_pcie_rp_x4_gen2 \"PF_PCIE_RP\" \"pcie_rp_x4.tcl\"   # x4 Gen2 root port"
puts ""
puts "Supported lanes: 1, 2, 4"
puts "Supported speeds: Gen1 (2.5 Gbps), Gen2 (5.0 Gbps)"
puts ""
puts "NOTE: This generator provides simplified configurations for common use cases."
puts "      For advanced PCIe features, use Libero GUI for full control."
