# ==============================================================================
# CoreUARTapb Configuration Generator
# ==============================================================================
#
# Purpose: Generate CoreUARTapb (UART with APB interface) configurations
# Usage:   source tcl_scripts/lib/generators/uart_config_generator.tcl
#
# ==============================================================================

# ==============================================================================
# UART Baud Rate Calculation
# ==============================================================================

proc calculate_baud_value {sys_clk_hz baud_rate} {
    # Calculate BAUD_VALUE for CoreUARTapb
    # Formula: BAUD_VALUE = (SYS_CLK / (BAUD_RATE * 16)) - 1

    set divisor [expr {$sys_clk_hz / ($baud_rate * 16)}]
    set baud_value [expr {$divisor - 1}]

    # Validate range (1 to 8191)
    if {$baud_value < 1} {
        puts "WARNING: Calculated BAUD_VALUE=$baud_value is too low (min=1)"
        set baud_value 1
    } elseif {$baud_value > 8191} {
        puts "WARNING: Calculated BAUD_VALUE=$baud_value is too high (max=8191)"
        set baud_value 8191
    }

    # Calculate actual baud rate
    set actual_baud [expr {$sys_clk_hz / (16 * ($baud_value + 1))}]
    set error_pct [expr {abs(($actual_baud - $baud_rate) * 100.0 / $baud_rate)}]

    puts "INFO: Baud Rate Configuration"
    puts "  System Clock: $sys_clk_hz Hz"
    puts "  Target Baud Rate: $baud_rate bps"
    puts "  BAUD_VALUE: $baud_value"
    puts "  Actual Baud Rate: $actual_baud bps"
    puts "  Error: [format %.2f $error_pct]%"

    if {$error_pct > 2.0} {
        puts "WARNING: Baud rate error > 2%, may cause communication issues"
    }

    return $baud_value
}

# ==============================================================================
# Main UART Configuration Generator
# ==============================================================================

proc generate_uart_config {args} {
    # Generate CoreUARTapb configuration

    array set opts {
        -sys_clk_hz "50000000"
        -baud_rate "115200"
        -data_bits "8"
        -parity "none"
        -rx_fifo "enable"
        -tx_fifo "enable"
        -component_name "CoreUARTapb_C0"
        -output_file ""
    }

    foreach {key value} $args {
        if {[info exists opts($key)]} {
            set opts($key) $value
        } else {
            puts "ERROR: Unknown option $key"
            return
        }
    }

    # Calculate baud rate divisor
    set baud_value [calculate_baud_value $opts(-sys_clk_hz) $opts(-baud_rate)]

    # Map data bits (8-bit mode flag)
    set prg_bit8 [expr {$opts(-data_bits) == "8" ? 1 : 0}]

    # Map parity
    set prg_parity 0
    switch $opts(-parity) {
        "none" { set prg_parity 0 }
        "odd"  { set prg_parity 1 }
        "even" { set prg_parity 2 }
        default {
            puts "WARNING: Unknown parity '$opts(-parity)', using 'none'"
            set prg_parity 0
        }
    }

    # Map FIFO enables
    set rx_fifo_en [expr {$opts(-rx_fifo) == "enable" ? 1 : 0}]
    set tx_fifo_en [expr {$opts(-tx_fifo) == "enable" ? 1 : 0}]

    # Generate configuration
    set config "# Exporting Component Description of $opts(-component_name) to TCL\n"
    append config "# Auto-generated by UART Configuration Generator\n"
    append config "# Configuration: $opts(-baud_rate) baud, $opts(-data_bits) data bits, $opts(-parity) parity\n"
    append config "# System Clock: $opts(-sys_clk_hz) Hz\n"
    append config "# Family: PolarFire\n"
    append config "create_and_configure_core -core_vlnv Actel:DirectCore:CoreUARTapb:* -component_name {$opts(-component_name)} -params {\\\n"

    append config "\"BAUD_VAL_FRCTN:0\"  \\\n"
    append config "\"BAUD_VAL_FRCTN_EN:false\"  \\\n"
    append config "\"BAUD_VALUE:$baud_value\"  \\\n"
    append config "\"FIXEDMODE:0\"  \\\n"
    append config "\"PRG_BIT8:$prg_bit8\"  \\\n"
    append config "\"PRG_PARITY:$prg_parity\"  \\\n"
    append config "\"RX_FIFO:$rx_fifo_en\"  \\\n"
    append config "\"RX_LEGACY_MODE:0\"  \\\n"
    append config "\"TX_FIFO:$tx_fifo_en\"  \\\n"
    append config "\"USE_SOFT_FIFO:0\"   }\n"

    append config "# Exporting Component Description of $opts(-component_name) to TCL done\n"

    # Output
    if {$opts(-output_file) != ""} {
        set fp [open $opts(-output_file) w]
        puts $fp $config
        close $fp
        puts "Generated UART configuration: $opts(-output_file)"
        puts "  Baud Rate: $opts(-baud_rate) bps"
        puts "  Data Bits: $opts(-data_bits)"
        puts "  Parity: $opts(-parity)"
        puts "  FIFOs: RX=$opts(-rx_fifo), TX=$opts(-tx_fifo)"
    } else {
        puts $config
    }

    return $config
}

# ==============================================================================
# Convenience Functions for Common Configurations
# ==============================================================================

proc generate_uart_115200 {{component_name "CoreUARTapb_C0"} {output_file ""}} {
    # Standard 115200 baud UART for 50 MHz system
    generate_uart_config \
        -sys_clk_hz "50000000" \
        -baud_rate "115200" \
        -data_bits "8" \
        -parity "none" \
        -rx_fifo "enable" \
        -tx_fifo "enable" \
        -component_name $component_name \
        -output_file $output_file
}

proc generate_uart_9600 {{component_name "CoreUARTapb_C0"} {output_file ""}} {
    # Standard 9600 baud UART for 50 MHz system
    generate_uart_config \
        -sys_clk_hz "50000000" \
        -baud_rate "9600" \
        -data_bits "8" \
        -parity "none" \
        -rx_fifo "enable" \
        -tx_fifo "enable" \
        -component_name $component_name \
        -output_file $output_file
}

proc generate_uart_460800 {{component_name "CoreUARTapb_C0"} {output_file ""}} {
    # High-speed 460800 baud UART for 50 MHz system
    generate_uart_config \
        -sys_clk_hz "50000000" \
        -baud_rate "460800" \
        -data_bits "8" \
        -parity "none" \
        -rx_fifo "enable" \
        -tx_fifo "enable" \
        -component_name $component_name \
        -output_file $output_file
}

proc generate_uart_custom {sys_clk_hz baud_rate {component_name "CoreUARTapb_C0"} {output_file ""}} {
    # Custom baud rate UART
    generate_uart_config \
        -sys_clk_hz $sys_clk_hz \
        -baud_rate $baud_rate \
        -data_bits "8" \
        -parity "none" \
        -rx_fifo "enable" \
        -tx_fifo "enable" \
        -component_name $component_name \
        -output_file $output_file
}

puts "CoreUARTapb Configuration Generator loaded"
puts "Usage:"
puts "  generate_uart_config -sys_clk_hz \"50000000\" -baud_rate \"115200\" -output_file \"my_uart.tcl\""
puts ""
puts "Convenience functions:"
puts "  generate_uart_115200 \"CoreUARTapb_C0\" \"output.tcl\"   # 115200 baud (standard)"
puts "  generate_uart_9600 \"CoreUARTapb_C0\" \"output.tcl\"     # 9600 baud"
puts "  generate_uart_460800 \"CoreUARTapb_C0\" \"output.tcl\"   # 460800 baud (high speed)"
puts "  generate_uart_custom 50000000 57600 \"CoreUARTapb_C0\" \"output.tcl\""
puts ""
puts "Common baud rates: 9600, 19200, 38400, 57600, 115200, 230400, 460800, 921600"
