# Exporting Component Description of PF_PCIE_RP_X4 to TCL
# Auto-generated by PCIe Configuration Generator
# Configuration: Root Port, x4 lanes, Gen2 (5.0 Gbps)
# BAR0: 2 GB, Device ID: 0x1556
# Family: PolarFire or PolarFireSoC
create_and_configure_core -core_vlnv {Actel:SgCore:PF_PCIE:*} -component_name {PF_PCIE_RP_X4} -params {\
"EXPOSE_ALL_DEBUG_PORTS:false"  \
"UI_DLL_JITTER_TOLERANCE:Medium_Low"  \
"UI_EXPOSE_LANE_DRI_PORTS:true"  \
"UI_IS_CONFIGURED:true"  \
"UI_PCIE_0_CONTROLLER_ENABLED:Disabled"  \
"UI_PCIE_1_BAR_MODE:Custom"  \
"UI_PCIE_1_CDR_REF_CLK_NUMBER:1"  \
"UI_PCIE_1_CDR_REF_CLK_SOURCE:Dedicated"  \
"UI_PCIE_1_CLASS_CODE:0x0604"  \
"UI_PCIE_1_CONTROLLER_ENABLED:Enabled"  \
"UI_PCIE_1_DE_EMPHASIS:-3.5 dB"  \
"UI_PCIE_1_DEVICE_ID:0x1556"  \
"UI_PCIE_1_EXPOSE_WAKE_SIG:Disabled"  \
"UI_PCIE_1_INTERRUPTS:MSI8"  \
"UI_PCIE_1_L0_ACC_LATENCY:No limit"  \
"UI_PCIE_1_L0_EXIT_LATENCY:64 ns to less than 128 ns"  \
"UI_PCIE_1_L1_ACC_LATENCY:No limit"  \
"UI_PCIE_1_L1_ENABLE:Disabled"  \
"UI_PCIE_1_L1_EXIT_LATENCY:16 us to less than 32 us"  \
"UI_PCIE_1_LANE_RATE:Gen2 (5.0 Gbps)"  \
"UI_PCIE_1_MASTER_SIZE_BAR_0_TABLE:2 GB"  \
"UI_PCIE_1_MASTER_TYPE_BAR_0_TABLE:64-bit prefetchable memory"  \
"UI_PCIE_1_MASTER_SIZE_BAR_1_TABLE:4 KB"  \
"UI_PCIE_1_MASTER_TYPE_BAR_1_TABLE:Disabled"  \
"UI_PCIE_1_MASTER_SIZE_BAR_2_TABLE:4 KB"  \
"UI_PCIE_1_MASTER_TYPE_BAR_2_TABLE:Disabled"  \
"UI_PCIE_1_MASTER_SIZE_BAR_3_TABLE:4 KB"  \
"UI_PCIE_1_MASTER_TYPE_BAR_3_TABLE:Disabled"  \
"UI_PCIE_1_MASTER_SIZE_BAR_4_TABLE:4 KB"  \
"UI_PCIE_1_MASTER_TYPE_BAR_4_TABLE:Disabled"  \
"UI_PCIE_1_MASTER_SIZE_BAR_5_TABLE:4 KB"  \
"UI_PCIE_1_MASTER_TYPE_BAR_5_TABLE:Disabled"  \
"UI_PCIE_1_NUM_FTS:63"  \
"UI_PCIE_1_NUMBER_OF_LANES:x4"  \
"UI_PCIE_1_PHY_REF_CLK_SLOT:Slot"  \
"UI_PCIE_1_PORT_TYPE:Root Port"  \
"UI_PCIE_1_REF_CLK_FREQ:100"  \
"UI_PCIE_1_REVISION_ID:0x0000"  \
"UI_PCIE_1_SLAVE_STATE_TABLE_0:Enabled"  \
"UI_PCIE_1_SLAVE_STATE_TABLE_1:Disabled"  \
"UI_PCIE_1_SLAVE_STATE_TABLE_2:Disabled"  \
"UI_PCIE_1_SLAVE_STATE_TABLE_3:Disabled"  \
"UI_PCIE_1_SLAVE_STATE_TABLE_4:Disabled"  \
"UI_PCIE_1_SLAVE_STATE_TABLE_5:Disabled"  \
"UI_PCIE_1_SLAVE_STATE_TABLE_6:Disabled"  \
"UI_PCIE_1_SLAVE_STATE_TABLE_7:Disabled"  \
"UI_PCIE_1_SUB_SYSTEM_ID:0x0000"  \
"UI_PCIE_1_SUB_VENDOR_ID:0x0000"  \
"UI_PCIE_1_TRANSMIT_SWING:Full Swing"  \
"UI_PCIE_1_VENDOR_ID:0x11AA"  \
"UI_PCIESS_LANE0_IS_USED:true"  \
"UI_PCIESS_LANE1_IS_USED:true"  \
"UI_PCIESS_LANE2_IS_USED:true"  \
"UI_PCIESS_LANE3_IS_USED:true"  \
"UI_GPSS1_LANE0_IS_USED:false"  \
"UI_GPSS1_LANE1_IS_USED:false"  \
"UI_GPSS1_LANE2_IS_USED:false"  \
"UI_GPSS1_LANE3_IS_USED:false"  \
"UI_PROTOCOL_PRESET_USED:PCIe"  \
"UI_SIMULATION_LEVEL:RTL"  \
"UI_TX_CLK_DIV_FACTOR:1"  \
"UI_USE_EMBEDDED_DLL:true"  \
"XT_ES_DEVICE:false"   }
# Exporting Component Description of PF_PCIE_RP_X4 to TCL done
# NOTE: This is a simplified configuration for common use cases.
#       For advanced features (AER, hotplug, ASPM, etc.), use Libero GUI.

