# Exporting Component Description of PF_PCIE_EP_X4 to TCL
# Auto-generated by PCIe Configuration Generator
# Configuration: Endpoint, x4 lanes, Gen2 (2.5 Gbps)
# BAR0: 1 MB, Device ID: 0x1556
# Family: PolarFire or PolarFireSoC
create_and_configure_core -core_vlnv {Actel:SgCore:PF_PCIE:*} -component_name {PF_PCIE_EP_X4} -params {\
"EXPOSE_ALL_DEBUG_PORTS:false"  \
"UI_DLL_JITTER_TOLERANCE:Medium_Low"  \
"UI_EXPOSE_LANE_DRI_PORTS:true"  \
"UI_IS_CONFIGURED:true"  \
"UI_PCIE_0_BAR_MODE:Custom"  \
"UI_PCIE_0_CDR_REF_CLK_NUMBER:1"  \
"UI_PCIE_0_CDR_REF_CLK_SOURCE:Dedicated"  \
"UI_PCIE_0_CLASS_CODE:0x0000"  \
"UI_PCIE_0_CONTROLLER_ENABLED:Enabled"  \
"UI_PCIE_0_DE_EMPHASIS:-3.5 dB"  \
"UI_PCIE_0_DEVICE_ID:0x1556"  \
"UI_PCIE_0_EXPOSE_WAKE_SIG:Disabled"  \
"UI_PCIE_0_INTERRUPTS:MSI1"  \
"UI_PCIE_0_L0_ACC_LATENCY:No limit"  \
"UI_PCIE_0_L0_EXIT_LATENCY:64 ns to less than 128 ns"  \
"UI_PCIE_0_L1_ACC_LATENCY:No limit"  \
"UI_PCIE_0_L1_ENABLE:Disabled"  \
"UI_PCIE_0_L1_EXIT_LATENCY:16 us to less than 32 us"  \
"UI_PCIE_0_LANE_RATE:Gen2 (2.5 Gbps)"  \
"UI_PCIE_0_MASTER_SIZE_BAR_0_TABLE:1 MB"  \
"UI_PCIE_0_MASTER_TYPE_BAR_0_TABLE:64-bit prefetchable memory"  \
"UI_PCIE_0_MASTER_SIZE_BAR_1_TABLE:4 KB"  \
"UI_PCIE_0_MASTER_TYPE_BAR_1_TABLE:Disabled"  \
"UI_PCIE_0_MASTER_SIZE_BAR_2_TABLE:4 KB"  \
"UI_PCIE_0_MASTER_TYPE_BAR_2_TABLE:Disabled"  \
"UI_PCIE_0_MASTER_SIZE_BAR_3_TABLE:4 KB"  \
"UI_PCIE_0_MASTER_TYPE_BAR_3_TABLE:Disabled"  \
"UI_PCIE_0_MASTER_SIZE_BAR_4_TABLE:4 KB"  \
"UI_PCIE_0_MASTER_TYPE_BAR_4_TABLE:Disabled"  \
"UI_PCIE_0_MASTER_SIZE_BAR_5_TABLE:4 KB"  \
"UI_PCIE_0_MASTER_TYPE_BAR_5_TABLE:Disabled"  \
"UI_PCIE_0_NUM_FTS:63"  \
"UI_PCIE_0_NUMBER_OF_LANES:x4"  \
"UI_PCIE_0_PHY_REF_CLK_SLOT:Slot"  \
"UI_PCIE_0_PORT_TYPE:End Point"  \
"UI_PCIE_0_REF_CLK_FREQ:100"  \
"UI_PCIE_0_REVISION_ID:0x0000"  \
"UI_PCIE_0_SLAVE_STATE_TABLE_0:Disabled"  \
"UI_PCIE_0_SLAVE_STATE_TABLE_1:Disabled"  \
"UI_PCIE_0_SLAVE_STATE_TABLE_2:Disabled"  \
"UI_PCIE_0_SLAVE_STATE_TABLE_3:Disabled"  \
"UI_PCIE_0_SLAVE_STATE_TABLE_4:Disabled"  \
"UI_PCIE_0_SLAVE_STATE_TABLE_5:Disabled"  \
"UI_PCIE_0_SLAVE_STATE_TABLE_6:Disabled"  \
"UI_PCIE_0_SLAVE_STATE_TABLE_7:Disabled"  \
"UI_PCIE_0_SUB_SYSTEM_ID:0x0000"  \
"UI_PCIE_0_SUB_VENDOR_ID:0x0000"  \
"UI_PCIE_0_TRANSMIT_SWING:Full Swing"  \
"UI_PCIE_0_VENDOR_ID:0x11AA"  \
"UI_PCIE_1_CONTROLLER_ENABLED:Disabled"  \
"UI_PCIESS_LANE0_IS_USED:true"  \
"UI_PCIESS_LANE1_IS_USED:true"  \
"UI_PCIESS_LANE2_IS_USED:true"  \
"UI_PCIESS_LANE3_IS_USED:true"  \
"UI_GPSS1_LANE0_IS_USED:false"  \
"UI_GPSS1_LANE1_IS_USED:false"  \
"UI_GPSS1_LANE2_IS_USED:false"  \
"UI_GPSS1_LANE3_IS_USED:false"  \
"UI_PROTOCOL_PRESET_USED:PCIe"  \
"UI_SIMULATION_LEVEL:RTL"  \
"UI_TX_CLK_DIV_FACTOR:1"  \
"UI_USE_EMBEDDED_DLL:true"  \
"XT_ES_DEVICE:false"   }
# Exporting Component Description of PF_PCIE_EP_X4 to TCL done
# NOTE: This is a simplified configuration for common use cases.
#       For advanced features (multiple BARs, MSI-X, AER, etc.), use Libero GUI.

