# Exporting core PF_CCC_MIV_C0 to TCL
# Configuration: 50 MHz → 50 MHz
# Auto-generated by CCC Configuration Generator
create_and_configure_core -core_vlnv {Actel:SgCore:PF_CCC:*} -download_core -component_name {PF_CCC_MIV_C0} -params {\
"DLL_CLK_0_BANKCLK_EN:false"  \
"DLL_CLK_0_DEDICATED_EN:false"  \
"DLL_CLK_0_FABCLK_EN:false"  \
"DLL_CLK_1_BANKCLK_EN:false"  \
"DLL_CLK_1_DEDICATED_EN:false"  \
"DLL_CLK_1_FABCLK_EN:false"  \
"DLL_CLK_P_EN:false"  \
"DLL_CLK_P_OPTIONS_EN:false"  \
"DLL_CLK_REF_OPTION:DIVIDE_BY_1"  \
"DLL_CLK_REF_OPTIONS_EN:false"  \
"DLL_CLK_S_EN:false"  \
"DLL_CLK_S_OPTION:DIVIDE_BY_1"  \
"DLL_CLK_S_OPTIONS_EN:false"  \
"GL0_0_BANKCLK_USED:false"  \
"GL0_0_BYPASS:0"  \
"GL0_0_BYPASS_EN:false"  \
"GL0_0_DEDICATED_USED:false"  \
"GL0_0_DIV:1"  \
"GL0_0_DIVSTART:0"  \
"GL0_0_FABCLK_GATED_USED:false"  \
"GL0_0_FABCLK_USED:true"  \
"GL0_0_IS_USED:true"  \
"GL0_0_OUT_FREQ:50"  \
"GL0_0_PHASE_INDEX:0"  \
"GL0_1_IS_USED:false"  \
"GL0_1_FABCLK_USED:false"  \
"GL1_0_IS_USED:false"  \
"GL1_0_FABCLK_USED:false"  \
"GL1_1_IS_USED:false"  \
"GL1_1_FABCLK_USED:false"  \
"GL2_0_IS_USED:false"  \
"GL2_0_FABCLK_USED:false"  \
"GL2_1_IS_USED:false"  \
"GL2_1_FABCLK_USED:false"  \
"GL3_0_IS_USED:false"  \
"GL3_0_FABCLK_USED:false"  \
"GL3_1_IS_USED:false"  \
"GL3_1_FABCLK_USED:false"  \
"PLL_IN_FREQ_0:50"  \
"PLL_FEEDBACK_MODE_0:Post-VCO"  \
"PLL_VCO_MODE_0:MIN_JITTER"  \
"PLL_REFDIV_0:4"  }
# Exporting core PF_CCC_MIV_C0 to TCL done

