# Exporting core PF_CCC_MIV_DDR_C1 to TCL
# Configuration: 50 MHz → 50 MHz (OUT0) + 200 MHz (OUT1)
# Auto-generated by CCC Configuration Generator
# PLL: VCO=200 MHz, Multiplier=4, Div0=4, Div1=1
create_and_configure_core -core_vlnv {Actel:SgCore:PF_CCC:*} -download_core -component_name {PF_CCC_MIV_DDR_C1} -params {\
"DLL_CLK_0_BANKCLK_EN:false"  \
"DLL_CLK_0_DEDICATED_EN:false"  \
"DLL_CLK_0_FABCLK_EN:false"  \
"DLL_CLK_1_BANKCLK_EN:false"  \
"DLL_CLK_1_DEDICATED_EN:false"  \
"DLL_CLK_1_FABCLK_EN:false"  \
"DLL_CLK_P_EN:false"  \
"GL0_0_BANKCLK_USED:false"  \
"GL0_0_DIV:4"  \
"GL0_0_FABCLK_USED:true"  \
"GL0_0_IS_USED:true"  \
"GL0_0_OUT_FREQ:50"  \
"GL0_1_BANKCLK_USED:false"  \
"GL0_1_DIV:1"  \
"GL0_1_FABCLK_USED:true"  \
"GL0_1_IS_USED:true"  \
"GL0_1_OUT_FREQ:200"  \
"GL1_0_IS_USED:false"  \
"GL1_0_FABCLK_USED:false"  \
"GL1_1_IS_USED:false"  \
"GL1_1_FABCLK_USED:false"  \
"GL2_0_IS_USED:false"  \
"GL2_0_FABCLK_USED:false"  \
"GL2_1_IS_USED:false"  \
"GL2_1_FABCLK_USED:false"  \
"GL3_0_IS_USED:false"  \
"GL3_0_FABCLK_USED:false"  \
"GL3_1_IS_USED:false"  \
"GL3_1_FABCLK_USED:false"  \
"PLL_IN_FREQ_0:50"  \
"PLL_FEEDBACK_MODE_0:Post-VCO"  \
"PLL_VCO_MODE_0:MIN_JITTER"  \
"PLL_REFDIV_0:4"  }
# Exporting core PF_CCC_MIV_DDR_C1 to TCL done
# NOTE: This is a simplified configuration. For production use, verify in Libero GUI.

