# Exporting Component Description of CoreUARTapb_9600 to TCL
# Auto-generated by UART Configuration Generator
# Configuration: 9600 baud, 8 data bits, none parity
# System Clock: 50000000 Hz
# Family: PolarFire
create_and_configure_core -core_vlnv Actel:DirectCore:CoreUARTapb:* -component_name {CoreUARTapb_9600} -params {\
"BAUD_VAL_FRCTN:0"  \
"BAUD_VAL_FRCTN_EN:false"  \
"BAUD_VALUE:324"  \
"FIXEDMODE:0"  \
"PRG_BIT8:1"  \
"PRG_PARITY:0"  \
"RX_FIFO:1"  \
"RX_LEGACY_MODE:0"  \
"TX_FIFO:1"  \
"USE_SOFT_FIFO:0"   }
# Exporting Component Description of CoreUARTapb_9600 to TCL done

