#!/usr/bin/env python3
"""
Generate hw_platform.h from Libero Memory Map JSON Export

Usage:
    python3 generate_hw_platform.py <memory_map.json> [output.h]

Description:
    Parses Libero's exported memory map JSON and generates a C header file
    with peripheral base address definitions suitable for embedded firmware.

Author: TCL Monster automation toolkit
"""

import json
import sys
from pathlib import Path
from datetime import datetime


def parse_memory_map(json_file):
    """Parse Libero memory map JSON and extract base addresses."""
    with open(json_file, 'r') as f:
        data = json.load(f)

    peripherals = []

    # Extract project info
    project_name = data.get('project_name', 'Unknown')
    smartdesign_name = data.get('SmartDesign name', 'Unknown')

    # Recursive function to walk the tree and find all peripherals (Type == "Target")
    def extract_targets(nodes):
        """Recursively extract all peripheral targets from nested structure."""
        targets = []
        if not isinstance(nodes, list):
            return targets

        for node in nodes:
            node_type = node.get('Type', '')
            component_name = node.get('Component name', '')
            offset_addr = node.get('Offset Address', '')

            # If this is a target peripheral with address, add it
            if node_type == 'Target' and component_name and offset_addr:
                # Clean up address format: remove underscores (0x7000_0000 → 0x70000000)
                clean_addr = offset_addr.replace('_', '')
                targets.append({
                    'name': component_name,
                    'base_addr': clean_addr
                })

            # Recursively process any connected nodes
            connected = node.get('Connected Node', [])
            if connected:
                targets.extend(extract_targets(connected))

        return targets

    # Parse initiator/target connections
    # Format: "Initiator/Bus/Bridge/Target OffsetAddress Range HighAddress"
    connections = data.get('Initiator/Bus/Bridge/Target OffsetAddress Range HighAddress', [])
    peripherals = extract_targets(connections)

    return {
        'project_name': project_name,
        'smartdesign_name': smartdesign_name,
        'peripherals': peripherals
    }


def generate_header(memory_map, output_file):
    """Generate hw_platform.h C header file."""

    project_name = memory_map['project_name']
    smartdesign_name = memory_map['smartdesign_name']
    peripherals = memory_map['peripherals']

    # Generate header content
    header = f"""/*******************************************************************************
 * Auto-generated by TCL Monster
 *
 * @file hw_platform.h
 * @brief Hardware platform definitions for {smartdesign_name}
 *
 * Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
 * Project: {project_name}
 * SmartDesign: {smartdesign_name}
 *
 * IMPORTANT: This file is auto-generated from Libero memory map export.
 * Do not edit manually - regenerate from updated Libero design instead.
 ******************************************************************************/

#ifndef HW_PLATFORM_H_
#define HW_PLATFORM_H_

/******************************************************************************
 * Peripheral Base Addresses
 *
 * These addresses are extracted from the SmartDesign memory map.
 * Format: <COMPONENT_NAME>_BASE_ADDR
 *****************************************************************************/

"""

    # Add peripheral base addresses
    if peripherals:
        for peripheral in peripherals:
            name = peripheral['name'].upper().replace('-', '_').replace(' ', '_')
            addr = peripheral['base_addr']

            # Ensure address is in proper hex format
            if not addr.startswith('0x'):
                addr = f"0x{addr}"

            header += f"#define {name}_BASE_ADDR{' ' * (40 - len(name))}({addr}UL)\n"
    else:
        header += "/* No peripherals found in memory map */\n"

    header += """
/******************************************************************************
 * System Clock Frequency
 *
 * TODO: Update this value based on your design's clock configuration
 *****************************************************************************/
#ifndef SYS_CLK_FREQ
#define SYS_CLK_FREQ                            50000000UL
#endif

/******************************************************************************
 * Baud Rate Calculations
 *****************************************************************************/
#define BAUD_VALUE_115200                       ((SYS_CLK_FREQ / (16 * 115200)) - 1)
#define BAUD_VALUE_57600                        ((SYS_CLK_FREQ / (16 * 57600)) - 1)

/******************************************************************************
 * STDIO UART Configuration (Optional)
 *
 * Uncomment and configure if you want printf/scanf redirected to UART
 *****************************************************************************/
/* #define MSCC_STDIO_THRU_CORE_UART_APB */
/* #define MSCC_STDIO_UART_BASE_ADDR          COREUARTAPB0_BASE_ADDR */
/* #define MSCC_STDIO_BAUD_VALUE              BAUD_VALUE_115200 */

#endif /* HW_PLATFORM_H_ */
"""

    # Write to file
    with open(output_file, 'w') as f:
        f.write(header)

    return output_file


def main():
    if len(sys.argv) < 2:
        print("ERROR: Missing required argument")
        print("")
        print("Usage:")
        print("  python3 generate_hw_platform.py <memory_map.json> [output.h]")
        print("")
        print("Example:")
        print("  python3 generate_hw_platform.py memory_map.json hw_platform.h")
        sys.exit(1)

    json_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "hw_platform.h"

    if not Path(json_file).exists():
        print(f"ERROR: Input file not found: {json_file}")
        sys.exit(1)

    print("=" * 60)
    print("TCL Monster: Hardware Platform Header Generator")
    print("=" * 60)
    print(f"Input:  {json_file}")
    print(f"Output: {output_file}")
    print("")

    try:
        # Parse memory map
        print("Parsing memory map...")
        memory_map = parse_memory_map(json_file)

        print(f"  Project: {memory_map['project_name']}")
        print(f"  SmartDesign: {memory_map['smartdesign_name']}")
        print(f"  Peripherals found: {len(memory_map['peripherals'])}")
        print("")

        # Generate header
        print("Generating header file...")
        output_path = generate_header(memory_map, output_file)

        print("")
        print(f"SUCCESS: Generated {output_path}")
        print("")
        print("Next steps:")
        print(f"  1. Review {output_file} for correctness")
        print("  2. Update SYS_CLK_FREQ if needed")
        print("  3. Copy to your firmware project:")
        print(f"     boards/<your-board>/hw_platform.h")
        print("")

        # Show generated definitions
        if memory_map['peripherals']:
            print("Generated definitions:")
            for p in memory_map['peripherals']:
                name = p['name'].upper().replace('-', '_').replace(' ', '_')
                print(f"  #define {name}_BASE_ADDR")

    except Exception as e:
        print(f"ERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
